const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const Application = require('../models/Application');
const authMiddleware = require('../middleware/authMiddleware');
const emailService = require('../utils/emailService');
const { logActivity } = require('../utils/logger');
const crypto = require('crypto');

// Multer Config
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, 'uploads/');
  },
  filename: (req, file, cb) => {
    cb(null, `${Date.now()}-${file.fieldname}${path.extname(file.originalname)}`);
  }
});

const upload = multer({
  storage: storage,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB
});

const cpUpload = upload.fields([
  { name: 'profilePicture', maxCount: 1 },
  { name: 'passportCopy', maxCount: 1 },
  { name: 'resume', maxCount: 1 },
  { name: 'transcript1', maxCount: 1 },
  { name: 'transcript2', maxCount: 1 },
  { name: 'transcript3', maxCount: 1 }
]);

// Submit a new application (Public)
router.post('/', cpUpload, async (req, res) => {
  try {
    const { 
      firstName,
      lastName,
      fullName, 
      certificateName, 
      dob, 
      gender, 
      email, 
      phone,
      passportNumber, 
      country,
      address,
      department,
      programme,
      courseStartDate,
      courseEndDate,
      intake,
      creditHours,
      price,
      registrationViaCentre,
      centreName,
      centreEmail,
      centrePhone,
      highestQualification
    } = req.body;

    // Check which documents are provided
    const profilePicturePath = req.files?.['profilePicture'] ? `/uploads/${req.files['profilePicture'][0].filename}` : '';
    const passportCopyPath = req.files?.['passportCopy'] ? `/uploads/${req.files['passportCopy'][0].filename}` : '';
    const resumePath = req.files?.['resume'] ? `/uploads/${req.files['resume'][0].filename}` : '';
    const transcript1Path = req.files?.['transcript1'] ? `/uploads/${req.files['transcript1'][0].filename}` : '';
    const transcript2Path = req.files?.['transcript2'] ? `/uploads/${req.files['transcript2'][0].filename}` : '';
    const transcript3Path = req.files?.['transcript3'] ? `/uploads/${req.files['transcript3'][0].filename}` : '';

    // Track which documents are missing (all 6 need to be uploaded)
    const missingDocuments = [];
    if (!profilePicturePath) missingDocuments.push('profilePicture');
    if (!passportCopyPath) missingDocuments.push('passportCopy');
    if (!resumePath) missingDocuments.push('resume');
    if (!transcript1Path) missingDocuments.push('transcript1');
    if (!transcript2Path) missingDocuments.push('transcript2');
    if (!transcript3Path) missingDocuments.push('transcript3');

    const computedFullName = fullName || `${firstName || ''} ${lastName || ''}`.trim();

    // Determine status and deadline (2 months when documents missing)
    let status = 'Submitted'; // All documents uploaded
    let documentDeadline = null;
    const submissionDate = new Date();

    if (missingDocuments.length > 0) {
      status = 'PendingDocuments';
      const dd = new Date(submissionDate);
      dd.setMonth(dd.getMonth() + 2); // 2 months from submission
      documentDeadline = dd;
    }

    // Generate reference number and unique token for user portal/status link
    const referenceNumber = `REF-${submissionDate.getTime().toString(36).toUpperCase()}`;
    const uniqueToken = crypto.randomBytes(12).toString('hex');

    const newApplication = new Application({
      firstName,
      lastName,
      fullName: computedFullName,
      certificateName,
      dob,
      gender,
      email,
      phone,
      passportNumber,
      country,
      address,
      department,
      programme,
      courseStartDate,
      courseEndDate,
      intake,
      creditHours,
      price,
      registrationViaCentre,
      centreName: registrationViaCentre === 'Yes' ? centreName : '',
      centreEmail: registrationViaCentre === 'Yes' ? centreEmail : '',
      centrePhone: registrationViaCentre === 'Yes' ? centrePhone : '',
      highestQualification,
      profilePicture: profilePicturePath,
      passportCopy: passportCopyPath,
      resume: resumePath,
      transcript1: transcript1Path,
      transcript2: transcript2Path,
      transcript3: transcript3Path,
      status,
      documentDeadline,
      missingDocuments,
      referenceNumber,
      uniqueToken,
      submissionDate,
      uploadLink: `${process.env.CLIENT_URL}/upload-documents/`
    });

    // Set uploadLink after ID is generated by mongoose (or we can just append _id)
    newApplication.uploadLink = `${process.env.CLIENT_URL}/upload-documents/${newApplication._id}`;

    const savedApplication = await newApplication.save();
    console.log(`[MongoDB] Successfully saved application for ${computedFullName} with ID ${savedApplication._id}`);

    const actionMsg = status === 'Submitted' 
      ? 'submitted with all documents' 
      : `submitted with pending documents (${missingDocuments.length} missing)`;
    
    await logActivity(
      'Application Submitted',
      `New application ${actionMsg} by ${computedFullName} for the ${programme} program`,
      'application',
      'User'
    );

    // If all documents were included, mark documentSubmittedAt/docsUploadedAt
    if (missingDocuments.length === 0) {
      savedApplication.documentSubmittedAt = submissionDate;
      savedApplication.docsUploadedAt = submissionDate;
      savedApplication.documentsUploadedCompleted = true;
      await savedApplication.save();
    }

    // Dispatch submission confirmation emails concurrently to user & admin
    try {
      await emailService.sendSubmissionEmails(savedApplication);
    } catch (mailErr) {
      console.error('[SMTP ERROR] Failed to send submission emails:', mailErr.message);
    }

    res.status(201).json({
      ...savedApplication.toObject(),
      message: status === 'Submitted' 
        ? 'Application submitted successfully!' 
        : `Application submitted. Please upload ${missingDocuments.length} remaining document(s) within 5 minutes.`
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server error');
  }
});

// Get all applications
router.get('/', authMiddleware, async (req, res) => {
  try {
    const applications = await Application.find().sort({ submissionDate: -1 });
    res.json(applications);
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server error');
  }
});

// Get a single application by ID (public, for document upload view)
router.get('/:id', async (req, res) => {
  try {
    const application = await Application.findById(req.params.id);
    if (!application) {
      return res.status(404).json({ message: 'Application not found' });
    }

    // Block if documents have already been uploaded
    if (application.documentsUploadedCompleted || application.status !== 'PendingDocuments') {
      return res.status(400).json({ message: 'Documents have already been uploaded for this email address. Multiple uploads are not allowed.' });
    }

    // Only return fields necessary for the document upload view
    res.json({
      _id: application._id,
      status: application.status,
      submissionDate: application.submissionDate,
      documentDeadline: application.documentDeadline,
      missingDocuments: application.missingDocuments
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server error');
  }
});

// Update application status
router.patch('/:id/status', authMiddleware, async (req, res) => {
  const { status } = req.body;
  
  if (!['Submitted', 'PendingDocuments', 'Reviewed', 'Accepted', 'Rejected'].includes(status)) {
    return res.status(400).json({ message: 'Invalid status value' });
  }

  try {
    const application = await Application.findById(req.params.id);
    
    if (!application) {
      return res.status(404).json({ message: 'Application not found' });
    }

    const previousStatus = application.status;
    application.status = status;
    await application.save();

    await logActivity(
      'Status Updated',
      `Application status of ${application.fullName} was changed from "${previousStatus}" to "${status}"`,
      'status',
      'Admin'
    );

    // Dispatch approval notifications simultaneously if transitioned to 'Accepted'
    // and the student registered through an approved center.
    if (status === 'Accepted' && previousStatus !== 'Accepted') {
      if (application.registrationViaCentre === 'Yes' && application.centreEmail) {
        try {
          await emailService.sendApprovalEmails(application);
        } catch (mailErr) {
          console.error('[SMTP ERROR] Failed to send approval emails:', mailErr.message);
        }
      }
    }

    res.json(application);
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server error');
  }
});

// Upload or attach documents to an existing application (public)
router.post('/:id/documents', cpUpload, async (req, res) => {
  try {
    const application = await Application.findById(req.params.id);
    if (!application) return res.status(404).json({ message: 'Application not found' });

    // Block if documents have already been uploaded
    if (application.documentsUploadedCompleted || application.status !== 'PendingDocuments') {
      return res.status(400).json({ message: 'Documents have already been uploaded for this email address. Multiple uploads are not allowed.' });
    }

    // If there is a deadline and it has passed, reject
    if (application.documentDeadline && application.documentDeadline < new Date()) {
      return res.status(400).json({ message: 'Document upload deadline has expired.' });
    }

    // Map uploaded files to application fields
    const fileMap = req.files || {};

    // Enforce that all currently missing documents must be uploaded in this request
    const missing = application.missingDocuments || [];
    const missingUploads = [];
    if (missing.includes('profilePicture') && !fileMap['profilePicture']) missingUploads.push('profilePicture');
    if (missing.includes('passportCopy') && !fileMap['passportCopy']) missingUploads.push('passportCopy');
    if (missing.includes('resume') && !fileMap['resume']) missingUploads.push('resume');
    if (missing.includes('transcript1') && !fileMap['transcript1']) missingUploads.push('transcript1');
    if (missing.includes('transcript2') && !fileMap['transcript2']) missingUploads.push('transcript2');
    if (missing.includes('transcript3') && !fileMap['transcript3']) missingUploads.push('transcript3');

    if (missingUploads.length > 0) {
      // Clean up uploaded files to prevent disk clutter
      const fs = require('fs');
      Object.keys(fileMap).forEach(fieldname => {
        fileMap[fieldname].forEach(file => {
          try {
            fs.unlinkSync(file.path);
          } catch (e) {
            console.error('Failed to delete uploaded file during clean-up:', e.message);
          }
        });
      });

      return res.status(400).json({ 
        message: `All missing documents must be uploaded together. Missing: ${missingUploads.join(', ')}` 
      });
    }

    if (fileMap['profilePicture']) application.profilePicture = `/uploads/${fileMap['profilePicture'][0].filename}`;
    if (fileMap['passportCopy']) application.passportCopy = `/uploads/${fileMap['passportCopy'][0].filename}`;
    if (fileMap['resume']) application.resume = `/uploads/${fileMap['resume'][0].filename}`;
    if (fileMap['transcript1']) application.transcript1 = `/uploads/${fileMap['transcript1'][0].filename}`;
    if (fileMap['transcript2']) application.transcript2 = `/uploads/${fileMap['transcript2'][0].filename}`;
    if (fileMap['transcript3']) application.transcript3 = `/uploads/${fileMap['transcript3'][0].filename}`;

    // Recompute missingDocuments
    const missing = [];
    if (!application.profilePicture) missing.push('profilePicture');
    if (!application.passportCopy) missing.push('passportCopy');
    if (!application.resume) missing.push('resume');
    if (!application.transcript1) missing.push('transcript1');
    if (!application.transcript2) missing.push('transcript2');
    if (!application.transcript3) missing.push('transcript3');

    application.missingDocuments = missing;

    if (missing.length === 0) {
      application.status = 'Submitted';
      application.documentDeadline = null;
      application.documentSubmittedAt = new Date();
      application.docsUploadedAt = new Date();
      application.documentsUploadedCompleted = true;
    } else {
      application.status = 'PendingDocuments';
      // keep existing deadline if present, otherwise set one to 2 months from submission
      if (!application.documentDeadline) {
        const d = new Date(application.submissionDate || Date.now());
        d.setMonth(d.getMonth() + 2);
        application.documentDeadline = d;
      }
    }

    const updated = await application.save();

    await logActivity('Documents Uploaded', `Documents uploaded for application ${updated._id} by ${updated.fullName}`, 'application', 'User');

    // Notify via email about updated submission state
    try {
      if (updated.documentsUploadedCompleted) {
        await emailService.sendDocumentUploadConfirmationEmails(updated);
      } else {
        await emailService.sendSubmissionEmails(updated);
      }
    } catch (mailErr) {
      console.error('[SMTP ERROR] Failed to send document-update emails:', mailErr.message);
    }

    res.json({ application: updated, message: missing.length === 0 ? 'All documents uploaded. Application complete.' : `Documents attached. ${missing.length} document(s) still pending.` });
  } catch (err) {
    console.error('Attach documents error', err.message);
    res.status(500).json({ message: 'Server error while attaching documents' });
  }
});

module.exports = router;
